/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Auto-generated from src/swatplus_ai/api/models.py. Do not edit — run `pnpm -C ui gen:types` to refresh.
 */
export interface SwatplusAiApi {}
/**
 * One citation attached to a finding or LLM response.
 *
 * This interface was referenced by `SwatplusAiApi`'s JSON-Schema
 * via the `definition` "Citation".
 */
export interface Citation {
  id: string;
  label: string;
  source: string;
}
/**
 * UI-shaped view of a :class:`~swatplus_ai.diagnostics.finding.Finding`.
 *
 * The domain ``Finding`` stores a rendered ``message`` plus raw evidence
 * (``dict``) and a rule-ref string; the UI wants a 4-panel layout (title
 * / evidence / explanation / suggestion) plus Citation records. The
 * adapter fills what the current domain has and leaves ``explanation``
 * and ``suggestion`` empty when the rule set doesn't provide them —
 * that gap is intentional and will close as rules grow richer.
 *
 * This interface was referenced by `SwatplusAiApi`'s JSON-Schema
 * via the `definition` "FindingVM".
 */
export interface FindingVM {
  citations: Citation[];
  evidence: string;
  explanation: string;
  id: string;
  location: string;
  ruleId: string;
  severity: "info" | "warning" | "error";
  suggestion: string;
  title: string;
}
/**
 * One class row in the Home landuse donut chart.
 *
 * This interface was referenced by `SwatplusAiApi`'s JSON-Schema
 * via the `definition` "LanduseSlice".
 */
export interface LanduseSlice {
  areaKm2: number;
  className: string;
  name: string;
  pct: number;
}
/**
 * Landing-page snapshot of a parsed SWAT+ project.
 *
 * Supersets :class:`~swatplus_ai.prompts.builder.ProjectSummary` with the
 * fields the UI Home screen asks for (outlet lat/lon, biome, ready-to-run
 * flag, etc.). Fields the current parser can't populate yet are typed as
 * ``str`` / ``float`` with empty-string or ``0.0`` defaults rather than
 * ``Optional`` so the TS surface stays simple — the UI can render ``""``
 * as "unknown" without adding null checks to every label.
 *
 * This interface was referenced by `SwatplusAiApi`'s JSON-Schema
 * via the `definition` "ProjectMeta".
 */
export interface ProjectMeta {
  areaKm2: number;
  biome: string;
  channels: number;
  climate: string;
  hrus: number;
  modelVersion: string;
  name: string;
  outfallChannel: string;
  outletLat: number;
  outletLon: number;
  path: string;
  readyToRun: boolean;
  simulationEnd: string;
  simulationStart: string;
  subbasins: number;
  warmupYears: number;
  weatherStations: number;
}
